[package]
name = "rustils"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.27", default_features = false, features = [
    "x11",
], optional = true }

[features]
workspaces = ["winit"]

[[bin]]
name = "workspaces"
required-features = ["workspaces"]
